name: 'ellipse'
model:
  epsilon: 0.1
  batch_size: 50
  gamma: 0.9
  learning_rate: 0.00025
  synchro_time: 100
  weight_name: 'weight.pth'
  test_anim_name: 'test.GIF'
  warm_up_anim_name: 'warm_up.GIF'
  reward_fig_name: 'reward.png'
  test_reward_fig_name: 'reward.png'
  loss_fig_name: 'loss.png'
  anim_interval: 25
  train_anim_show: False

env: 
  init_wide: 2.0
  init_height: 1.0
  max_episode: 100
  max_epoch: 100
  warm_up_epoch: 100
  round_digit: 2
